version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  cadvisor:
    image: google/cadvisor:latest
    container_name: db1_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "9101:9101"
    labels:
      - "mon.percona.container_type=collector"

  mysqld_exporter_high_res:
    image: prom/mysqld-exporter:latest
    container_name: db1_mysqld_exporter_hres
    environment:
      DATA_SOURCE_NAME: 'prom_exporter:X@(172.31.17.153:3306)/'
    ports:
      - "9104:9104"
    command:
#      - '--help'
      - '--web.listen-address=:9104'
      - '--collect.global_status'
#    command: ["--web.listen-address=:9104", "-collect.global_status=true", "--collect.global_variables=false", "--collect.slave_status=false", "--collect.info_schema.tables=false", "--collect.binlog_size=false", "--collect.info_schema.processlist=false", "--collect.info_schema.userstats=false", "--collect.info_schema.tables=false", "--collect.auto_increment.columns=false", "--collect.info_schema.tablestats=false", "--collect.perf_schema.file_events=false", "--collect.perf_schema.eventsstatements=false", "--collect.perf_schema.indexiowaits=false", "--collect.perf_schema.tableiowaits=false", "--collect.perf_schema.tablelocks=false", "--collect.perf_schema.eventswaits=false"]
    labels:
      - "mon.percona.container_type=collector"
    depends_on:
      - db

volumes:
    db_data: {}
